language: php
dist: trusty

jobs:
  include:
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "nightly"
    - php: "hhvm"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --no-interaction --prefer-source

# vim:ts=2:sw=2:et
